加入開始日期和結束日期的變數
Shihyen/gcloud_integration pull request #1
Opened 2019-10-05 07:18 UTC by mandy331

2019-10-06 10:37 UTC, Shihyen requested changes

2019-10-06 10:37 UTC, Shihyen commented on admanager/admanager.py
> +                if 'startDate' and 'endDate' in args[0]:
這樣的寫法會變成(startDate is True) and (endDate in args[0])
and 前後都要是邏輯運算

2019-10-06 10:37 UTC, Shihyen commented on admanager/admanager.py
>          if args[0] is not None:
可以把args[0]做比較好的處理
if args[0] is not None:
    params = args[0]

接下來就知道是在處理參數

2019-10-08 03:16 UTC, mandy331 commented on admanager/admanager.py
>          if args[0] is not None:
是有點像這樣嗎？
![image](https://user-images.githubusercontent.com/33720290/66364634-01cfd800-e9bd-11e9-8922-6cb2df86f632.png)

2019-10-08 13:59 UTC, Shihyen commented on admanager/admanager.py
>          if args[0] is not None:
ok

2019-10-08 14:00 UTC, merged