更新結構
Shihyen/gcloud_integration pull request #10
Opened 2020-01-13 13:25 UTC by mandy331

2020-01-13 14:32 UTC, Shihyen requested changes
主要的問題是啟動參數改為adreport就可以

2020-01-13 14:32 UTC, Shihyen commented on app.py
>      if type == 'admanager':
參數就改成adreport了，這樣才一致

2020-01-13 14:32 UTC, Shihyen commented on googlesheets/googlesheets.py
> +            column_df = self.default_template_sheet_column()
column_df 我以為是跟著不同campaign長度去產生？

2020-01-13 14:32 UTC, Shihyen commented on googlesheets/googlesheets.py
> -        spreadsheet_name = format_end_date + '_' + str(report["Dimension.ORDER_NAME"][0]) + '_成效'
Python裡盡量用 % 來format字串，或是用f-string(覺得難用

https://blog.louie.lu/2017/08/08/outdate-python-string-format-and-fstring/

2020-01-15 02:54 UTC, mandy331 commented on app.py
>      if type == 'admanager':
好喔，這個我去改！

2020-01-15 02:58 UTC, mandy331 commented on googlesheets/googlesheets.py
> +            column_df = self.default_template_sheet_column()
這個是預設的所有column欄位，一個對照表的概念，實際是會跟著campaign的長度去產生。

2020-01-15 02:58 UTC, mandy331 commented on googlesheets/googlesheets.py
> -        spreadsheet_name = format_end_date + '_' + str(report["Dimension.ORDER_NAME"][0]) + '_成效'
好，這邊我再改成%的格式。

2020-01-16 02:18 UTC, merged